version: '3'
services:
  site:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    environment:
      - JEKYLL_ENV=development
    command: >
      bash -c "bundle install && bundle exec jekyll clean && bundle exec jekyll serve --host 0.0.0.0 --livereload"

volumes:
  bundle_cache:
